<?php

namespace Database\Seeders;

use App\Models\Master\Pdam;
use App\Models\Master\Pelanggan;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class PelangganSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // $pelanggan =  new Pelanggan;
        // $pelanggan->nama = "Sawaludin";
        // $pelanggan->nik = "11224546456";
        // $pelanggan->kk = "4455662665";
        // $pelanggan->golongan_id = 1;
        // $pelanggan->lat = "4.629504850910602";
        // $pelanggan->long = "96.844175600882";
        // $pelanggan->nolama = 11122254;
        // $pelanggan->pdam_id = 1;
        // $pelanggan->desa_id = 3;
        // $pelanggan->user_id = 1;
        // $pelanggan->user_id_penyetuju = 1;
        // $pelanggan->save();


        // Pelanggan::insert([
        //     [
        //         'nama' => 'Iwan Darita',
        //         'nik' => "445565656",
        //         'kk' => "456456215",
        //         'golongan_id' => 1,

        //         'lat' => "",
        //         'long' => "",
        //         'pdam_id' => 1,
        //         'desa_id' => 3,
        //         'user_id' => 1,
        //         'user_id_penyetuju' => 1,
        //     ],
        //     [
        //         'nama' => 'Sulstri B',
        //         'nik' => "445565656",
        //         'kk' => "445565656",
        //         'golongan_id' => 1,
        //         'lat' => "4.629504850910602",
        //         'long' => "96.844175600882",
        //         'pdam_id' => 1,
        //         'desa_id' => 3, //kemili
        //         'user_id' => 1,
        //         'user_id_penyetuju' => 1,
        //     ],
        //     [
        //         'nama' => 'Ucok B',
        //         'nik' => "3435",
        //         'kk' => "22245666",
        //         'golongan_id' => 2,
        //         'lat' => "4.629504850910602",
        //         'long' => "96.844175600882",
        //         'pdam_id' => 1,
        //         'desa_id' => 3, //kemili
        //         'user_id' => 1,
        //         'user_id_penyetuju' => 1,
        //     ],
        //     [
        //         'nama' => 'Arwin',
        //         'nik' => "445565656",
        //         'kk' => "445565656",
        //         'golongan_id' => 1,
        //         'lat' => "",
        //         'long' => "",
        //         'pdam_id' => 1,
        //         'desa_id' => 1,  //pegasing
        //         'user_id' => 1,
        //         'user_id_penyetuju' => 1,
        //     ],

        // ]);

        Pelanggan::insert([

            ['nama' => 'A. ARMAYA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100023'],
            ['nama' => 'ABD. HAMID AJALI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100024'],
            ['nama' => 'BANTACUT', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100025'],
            ['nama' => 'ZAINAL BUHARI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100026'],
            ['nama' => 'BARIMSYAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100027'],
            ['nama' => 'YAPAN R', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100028'],
            ['nama' => 'M. NUR AB', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100029'],
            ['nama' => 'WR. MILA INDAH', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100030'],
            ['nama' => 'A. PENUH', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100031'],
            ['nama' => 'AFAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100032'],
            ['nama' => 'ISMAIL ST', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100033'],
            ['nama' => 'SELAMAT JEPANG ', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100034'],
            ['nama' => 'M. KASIM AMIN', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100035'],
            ['nama' => 'SARMIATI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100036'],
            ['nama' => 'ANWAR', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100037'],
            ['nama' => 'AMAN IS', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100038'],
            ['nama' => 'M SALIM', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100039'],
            ['nama' => 'M. DAUD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100040'],
            ['nama' => 'KTR. LURAH BLANG KOLAK I', 'nik' => '', 'kk' => '', 'golongan_id' => 5, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100041'],
            ['nama' => 'SYARIAH UMAR', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100042'],
            ['nama' => 'KANTOR PAJAK KP2KP', 'nik' => '', 'kk' => '', 'golongan_id' => 5, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100043'],
            ['nama' => 'IBRAHIM RB', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100044'],
            ['nama' => 'UCAK P & K', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100045'],
            ['nama' => 'UCAK JAKSA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100046'],
            ['nama' => 'ILYAS RS', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100047'],
            ['nama' => 'RUSMAWATI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100048'],
            ['nama' => 'BAGINDO KASIM / SABIRIN .HS', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100049'],
            ['nama' => 'ABU SAMAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100050'],
            ['nama' => 'KARBIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100051'],
            ['nama' => 'A. NUCAYA / SUPARTI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100052'],
            ['nama' => 'AJI SALEH 1', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100053'],
            ['nama' => 'AMAN SRI KAYA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100054'],
            ['nama' => 'ZUPRI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100055'],
            ['nama' => 'M. NASIR M', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100056'],
            ['nama' => 'A. FARIDA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100057'],
            ['nama' => 'ANWAR SADAT', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100058'],
            ['nama' => 'PADILAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100059'],
            ['nama' => 'H KASAH SYAMSUDDIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100060'],
            ['nama' => 'MISDAR, S.PD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100061'],
            ['nama' => 'FAJRIADI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100062'],
            ['nama' => 'HASIBA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100063'],
            ['nama' => 'ILYAS AYUS', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100064'],
            ['nama' => 'A. SELAMAT', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100065'],
            ['nama' => 'AMIRULLAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100066'],
            ['nama' => 'ITEM IYAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100067'],
            ['nama' => 'M. HUSIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100068'],
            ['nama' => 'ISMAIL M', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100069'],
            ['nama' => 'UJANG ARIF', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100070'],
            ['nama' => 'AHMAD AM', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100071'],
            ['nama' => 'WARNO WARIZI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100072'],
            ['nama' => 'A. HALIMAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100073'],
            ['nama' => 'MURAT', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100074'],
            ['nama' => 'ABD. MAS', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100075'],
            ['nama' => 'MANSYUR SYAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100076'],
            ['nama' => 'UMAR A', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100077'],
            ['nama' => 'A. ARSADI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100078'],
            ['nama' => 'A. RASUNAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100079'],
            ['nama' => 'RUSMANIAR', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100080'],
            ['nama' => 'HR. PUTIH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100081'],
            ['nama' => 'A. JELEKA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100082'],
            ['nama' => 'SUPIAN ARIF', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100083'],
            ['nama' => 'KAMARUDDIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100084'],
            ['nama' => 'DENI KAHARUDDIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100085'],
            ['nama' => 'M. SALEH AR', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100086'],
            ['nama' => 'ALI TORA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100087'],
            ['nama' => 'MUDIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100088'],
            ['nama' => 'ABD. RAHMAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100089'],
            ['nama' => 'A. KALIMAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100090'],
            ['nama' => 'ABD. HAMID', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100091'],
            ['nama' => 'MAR', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100092'],
            ['nama' => 'LUKMAN KARIM BSC', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100093'],
            ['nama' => 'AISYAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100094'],
            ['nama' => 'MUS WARIZI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100095'],
            ['nama' => 'HASBULLAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100096'],
            ['nama' => 'ABDULLAH IBRAHIM', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100097'],
            ['nama' => 'JAINUDDIN UMAR', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100098'],
            ['nama' => 'BURIAN', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100099'],
            ['nama' => 'ABD. KARIM MR', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100100'],
            ['nama' => 'FAJARUDDIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100101'],
            ['nama' => 'ILYAS GORDIAN', 'nik' => '', 'kk' => '', 'golongan_id' => 7, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100102'],
            ['nama' => 'MARMUJI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100103'],
            ['nama' => 'SUHATMAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100104'],
            ['nama' => 'USMAN MUHADDIN RSU', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100105'],
            ['nama' => 'ABD. JALIL', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100106'],
            ['nama' => 'SYAMSIAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100107'],
            ['nama' => 'DARWINSYAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100108'],
            ['nama' => 'ARIFIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100109'],
            ['nama' => 'SARIFAH UMAR 1', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100110'],
            ['nama' => 'JAYADI JUNAIDI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100111'],
            ['nama' => 'ZULKIFLI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100112'],
            ['nama' => 'PAK DATUK', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100113'],
            ['nama' => 'YUS', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100114'],
            ['nama' => 'SITI FATIMAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100115'],
            ['nama' => 'USMAN ', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100116'],
            ['nama' => 'M. HUSAINI G', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100117'],
            ['nama' => 'REMAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100118'],
            ['nama' => 'PAK UCOK', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100119'],
            ['nama' => 'ISLI IRIANTO/AISYAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100120'],
            ['nama' => 'IBU RAMIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100121'],
            ['nama' => 'RUSIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100122'],
            ['nama' => 'MUSTAMAM', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100123'],
            ['nama' => 'MAHDI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100124'],
            ['nama' => 'YAHMAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100125'],
            ['nama' => 'ISKANDAR', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100126'],
            ['nama' => 'M I S D I', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100127'],
            ['nama' => 'MAHENDRA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100128'],
            ['nama' => 'WASITO / MARSITOK', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100129'],
            ['nama' => 'DANIS DONAT', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100130'],
            ['nama' => 'KHAIRUDDIN. TV', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100131'],
            ['nama' => 'DAHLAN 1', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100132'],
            ['nama' => 'DAHLAN 2', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100133'],
            ['nama' => 'DAHLAN 3', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100134'],
            ['nama' => 'BIHARI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100135'],
            ['nama' => 'AMAN TAJUD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100136'],
            ['nama' => 'JUNAIDI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100137'],
            ['nama' => 'M. YUNUS', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100138'],
            ['nama' => 'IBRAHIM RB', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100139'],
            ['nama' => 'MURNI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100140'],
            ['nama' => 'ARIS', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100141'],
            ['nama' => 'BUNGKARDI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100142'],
            ['nama' => 'ASFARI', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100143'],
            ['nama' => 'ASRIL', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100144'],
            ['nama' => 'A. JHON', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100145'],
            ['nama' => 'Drs. IBRAHIM H. AZMI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100146'],
            ['nama' => 'ANWAR', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100147'],
            ['nama' => 'SUKARTINA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100148'],
            ['nama' => 'AFAN TGK. SULAIMAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100149'],
            ['nama' => 'AFFAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100150'],
            ['nama' => 'ZAINAP', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100151'],
            ['nama' => 'ABRAR GUNAWAN, ST, M. SI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100152'],
            ['nama' => 'HASBALLAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100153'],
            ['nama' => 'MENASAH JAWA/BELANG KOLAK 1', 'nik' => '', 'kk' => '', 'golongan_id' => 1, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100154'],
            ['nama' => 'RAIMAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100155'],
            ['nama' => 'RIDUANSYAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100156'],
            ['nama' => 'AISYAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100157'],
            ['nama' => 'JF. MANURUNG', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100158'],
            ['nama' => 'SYARIAH UMAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100159'],
            ['nama' => 'SYARIAH UMAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100160'],
            ['nama' => 'SYARIAH UMAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100161'],
            ['nama' => 'AMIR POS', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100162'],
            ['nama' => 'M.DAHLAN, SE.', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100163'],
            ['nama' => 'AJI MERAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100164'],
            ['nama' => 'ZULKIFLI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100165'],
            ['nama' => 'SUPRAFTO', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100166'],
            ['nama' => 'IR. TAGORE 2', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100167'],
            ['nama' => 'YENDI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100168'],
            ['nama' => 'M. ALAMSYAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100169'],
            ['nama' => 'ERI SUGROHO BUDI SANTOSO', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100170'],
            ['nama' => 'MUHTAR BUDIMAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100171'],
            ['nama' => 'ARAKSI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100172'],
            ['nama' => 'KHAIRUDDIN, SE. 2', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100173'],
            ['nama' => 'ASNI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100174'],
            ['nama' => 'ROBINO', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100175'],
            ['nama' => 'ZULKARNAIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100176'],
            ['nama' => 'KUSTIYANTI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100177'],
            ['nama' => 'SUYADI ASRI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100178'],
            ['nama' => 'KAIRUDDIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100179'],
            ['nama' => 'ANO', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100180'],
            ['nama' => 'H. ISMAI SULTAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100181'],
            ['nama' => 'USMAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100182'],
            ['nama' => 'ALAMSYAH/RATNA WATI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100183'],
            ['nama' => 'MASKURI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100184'],
            ['nama' => 'SALAM', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100185'],
            ['nama' => 'HUSIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100186'],
            ['nama' => 'MARIE WAHYUNI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100187'],
            ['nama' => 'MARJAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100188'],
            ['nama' => 'DAHLAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100189'],
            ['nama' => 'TUKIJAH YANTO', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100190'],
            ['nama' => 'IRBA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100191'],
            ['nama' => 'NANDAR', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100192'],
            ['nama' => 'M. ALI A. LUKMAN / DADONG', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100193'],
            ['nama' => 'WARMAN', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100194'],
            ['nama' => 'DARMAYAN SARAGIH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100195'],
            ['nama' => 'GIMIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100196'],
            ['nama' => 'M. ISA USMAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100197'],
            ['nama' => 'HILGA YZ', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100198'],
            ['nama' => 'ASNAWATI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100199'],
            ['nama' => 'H.HARUN AHMAT SABAR.2', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100200'],
            ['nama' => 'H.HARUN AHMAT SABAR.3', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100201'],
            ['nama' => 'SUKARYATI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100202'],
            ['nama' => 'MURTINA B.TOHANG', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100203'],
            ['nama' => 'H.BAKAR BUKIT.1', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100204'],
            ['nama' => 'H.BAKAR BUKIT.2', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100205'],
            ['nama' => 'DR.PADLAN/RS FANDIKA', 'nik' => '', 'kk' => '', 'golongan_id' => 8, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100206'],
            ['nama' => 'SAMAUN 1', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100207'],
            ['nama' => 'SAMAUN 2', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100208'],
            ['nama' => 'SAMAUN 3', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100209'],
            ['nama' => 'RAMLI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100210'],
            ['nama' => 'SYEH JALI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100211'],
            ['nama' => 'KAMALIAH 1', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100212'],
            ['nama' => 'DRS.SURADI.R', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100213'],
            ['nama' => 'MALIK MELALA TOA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100214'],
            ['nama' => 'JULI WANARA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100215'],
            ['nama' => 'AGUS SALIM', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100216'],
            ['nama' => 'ERFIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100217'],
            ['nama' => 'TASNIM,SH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100218'],
            ['nama' => 'AMIRUDDIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100219'],
            ['nama' => 'MAWARDI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100220'],
            ['nama' => 'H.ISMAIL SULTAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100221'],
            ['nama' => 'SITI AISYAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100222'],
            ['nama' => 'M.THAMRIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100223'],
            ['nama' => 'SAMARIAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100224'],
            ['nama' => 'SAJIDIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100225'],
            ['nama' => 'I N A', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100226'],
            ['nama' => 'MAULIDAR,SH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100227'],
            ['nama' => 'YANDI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100228'],
            ['nama' => 'DEFRI', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100229'],
            ['nama' => 'KHAIRUL BARIAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100230'],
            ['nama' => 'MULAWATI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100231'],
            ['nama' => 'EKA YUSA.1', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100232'],
            ['nama' => 'SUJATMOKO', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100233'],
            ['nama' => 'M.SALEH.AR', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100234'],
            ['nama' => 'RUSLAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100235'],
            ['nama' => 'MUHAMMAD DAHLAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100236'],
            ['nama' => 'ZAINAB YULIANTI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100237'],
            ['nama' => 'HOTEL BAYU HILL', 'nik' => '', 'kk' => '', 'golongan_id' => 8, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100238'],
            ['nama' => 'H.BAKAR BUKIT.3', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100239'],
            ['nama' => 'JHON', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100240'],
            ['nama' => 'SATINAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100241'],
            ['nama' => 'A H D I', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100242'],
            ['nama' => 'LAINAWATI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100243'],
            ['nama' => 'ROZALI BUDIMAN.1', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100244'],
            ['nama' => 'CENDRI NAFIS', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100245'],
            ['nama' => 'YANUAR NOVARA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100246'],
            ['nama' => 'SAMSUDDIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100247'],
            ['nama' => 'SAJIDIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100248'],
            ['nama' => 'BURIAN KALAM', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100249'],
            ['nama' => 'WARNO WARIZI', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100250'],
            ['nama' => 'SAHIL GUNAWAN', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100251'],
            ['nama' => 'WARNO WARIZI', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100252'],
            ['nama' => 'ISMAIL. HS', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100253'],
            ['nama' => 'TIGOR', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100254'],
            ['nama' => 'JALALUDDIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100255'],
            ['nama' => 'MULYA IRAWAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100256'],
            ['nama' => 'MHD.ADAM', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100257'],
            ['nama' => 'TRIFINA', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100258'],
            ['nama' => 'IWAN AZKA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100259'],
            ['nama' => 'AMIRUDDIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100260'],
            ['nama' => 'MARZUKI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100261'],
            ['nama' => 'ASWIN ARIFIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100262'],
            ['nama' => 'ARIES', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100263'],
            ['nama' => 'ZULKIFLI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100264'],
            ['nama' => 'SIGIT TUGIYO', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100265'],
            ['nama' => 'SALMAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100266'],
            ['nama' => 'AISYAH JAMIL', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100267'],
            ['nama' => 'MUHAMMAD.IB/NAGOYA', 'nik' => '', 'kk' => '', 'golongan_id' => 7, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100268'],
            ['nama' => 'SYAHRIAL MASKUR', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100269'],
            ['nama' => 'DEFRI', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100270'],
            ['nama' => 'DADONG', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100271'],
            ['nama' => 'SUHELMI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100272'],
            ['nama' => 'MULYADEWI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100273'],
            ['nama' => 'AHMAD SARWANI', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100274'],
            ['nama' => 'KAMINI.1', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100275'],
            ['nama' => 'KAMINI.2', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100276'],
            ['nama' => 'M.HUSAINI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100277'],
            ['nama' => 'IRHAMNA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100278'],
            ['nama' => 'AISYAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100279'],
            ['nama' => 'ASALUDDIN', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100280'],
            ['nama' => 'MISBAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100281'],
            ['nama' => 'CHAIRUL FAUZI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100282'],
            ['nama' => 'SYEH ALI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100283'],
            ['nama' => 'UCAK P.K', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100284'],
            ['nama' => 'RAHMIATI TAGORE.P', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100285'],
            ['nama' => 'MANSUR DAMA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100286'],
            ['nama' => 'ERFAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100287'],
            ['nama' => 'MASJID RAUDATUL JANNAH', 'nik' => '', 'kk' => '', 'golongan_id' => 1, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100288'],
            ['nama' => 'SAMSUL BAHRI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100289'],
            ['nama' => 'M. BASYIR', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100290'],
            ['nama' => 'I C U T', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100291'],
            ['nama' => 'SURYATI WAAS', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100292'],
            ['nama' => 'SUKARDI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100293'],
            ['nama' => 'JUMINAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100294'],
            ['nama' => 'KHAIRUDDIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100295'],
            ['nama' => 'M YUNUS (GUDANG ROSE FLOWERS)', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100296'],
            ['nama' => 'DALILAH, S.PD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100297'],
            ['nama' => 'TANWIR', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100298'],
            ['nama' => 'SUTARNO', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100299'],
            ['nama' => 'JASMAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100300'],
            ['nama' => 'BUSTAMI 1', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100301'],
            ['nama' => 'BUSTAMI 2', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100302'],
            ['nama' => 'BUSTAMI 3', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100303'],
            ['nama' => 'MULIADI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100304'],
            ['nama' => 'ANI MARANGIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100305'],
            ['nama' => 'SURYADI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100306'],
            ['nama' => 'ROSTANTIKA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100307'],
            ['nama' => 'ALI USMAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100308'],
            ['nama' => 'JONE FITRA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100309'],
            ['nama' => 'RISKA ASLOINDS', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100310'],
            ['nama' => 'SONY KURNIAWAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100311'],
            ['nama' => 'MARDIANA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100312'],
            ['nama' => 'HAJELAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100313'],
            ['nama' => 'SUWARNI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100314'],
            ['nama' => 'HASBI PARANG', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100315'],
            ['nama' => 'HALIMAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100316'],
            ['nama' => 'ANISYAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100317'],
            ['nama' => 'ARNISA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100318'],
            ['nama' => 'NURMADIAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100319'],
            ['nama' => 'SUKAINA ARAFAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100320'],
            ['nama' => 'DIBA QUINE SHINTA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '2', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100321'],
            ['nama' => 'AMIR HAMZAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100322'],
            ['nama' => 'IBRAHIM, SH / YUSRIADI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100323'],
            ['nama' => 'M YUSUF SUTRISMO', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100324'],
            ['nama' => 'RD WABUB A.TENGAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100325'],
            ['nama' => 'RD KETUA DPRK', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100326'],
            ['nama' => 'RD WAKIL DPRK 1', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100327'],
            ['nama' => 'RD WAKIL DPRK 2', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100328'],
            ['nama' => 'KARYADI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100329'],
            ['nama' => 'IBRAHIM MUDE', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100330'],
            ['nama' => 'SYAMSUL RIZAL', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100331'],
            ['nama' => 'HAMZAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100332'],
            ['nama' => 'DAHLAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100333'],
            ['nama' => 'IBRAHIM AHMAD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100334'],
            ['nama' => 'RD PT.KKA/M.JAMIL R', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100335'],
            ['nama' => 'ADNAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100336'],
            ['nama' => 'OTTO SAPACUAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100337'],
            ['nama' => 'SITOHANG ', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100338'],
            ['nama' => 'M ALAMSYAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100339'],
            ['nama' => 'M NASIR', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100340'],
            ['nama' => 'UDIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100341'],
            ['nama' => 'RD KARYAWAN PT.KKA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100342'],
            ['nama' => 'LINA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100343'],
            ['nama' => 'M JAFAR', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100344'],
            ['nama' => 'MOHD SUKRI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100345'],
            ['nama' => 'KATENA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100346'],
            ['nama' => 'ABD HADIS BENAR', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100347'],
            ['nama' => 'SUPARMAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100348'],
            ['nama' => 'ZULKIFLI, SE', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100349'],
            ['nama' => 'KARSOGI KROMOSO', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100350'],
            ['nama' => 'SUYANTO', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100351'],
            ['nama' => 'RAMLAH ISMAIL', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100352'],
            ['nama' => 'AMNIZAR RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100353'],
            ['nama' => 'ISMAIL B RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100354'],
            ['nama' => 'DARMAWI H RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100355'],
            ['nama' => 'SYAHYUDIN RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100356'],
            ['nama' => 'BIHER MANULANG RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100357'],
            ['nama' => 'EDI SUTONO RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100358'],
            ['nama' => 'ANDRI RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100359'],
            ['nama' => 'K.O. ALEXANDER RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100360'],
            ['nama' => 'MARUDDIN RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100361'],
            ['nama' => 'M BADRI RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100362'],
            ['nama' => 'HENDRI ANTOMI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100363'],
            ['nama' => 'FERI RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100364'],
            ['nama' => 'EMRI JUPRIANTO RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100365'],
            ['nama' => 'AFIFUDDIN RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100366'],
            ['nama' => 'MENROFA RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100367'],
            ['nama' => 'DALIAN PUTRA RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100368'],
            ['nama' => 'SOEHADI KS RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100369'],
            ['nama' => 'RM YUNUF RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100370'],
            ['nama' => 'SABA ATIWARU RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100371'],
            ['nama' => 'RONI MS SIREGAR RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100372'],
            ['nama' => 'SOFYAN YOESHA RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100373'],
            ['nama' => 'BOHARI RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100374'],
            ['nama' => 'SAHRIANTO RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100375'],
            ['nama' => 'P. GULTOM RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100376'],
            ['nama' => 'M DAHRIL ISKANDAR RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100377'],
            ['nama' => 'SUMARYANTO', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100378'],
            ['nama' => 'FAYAHATAN RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100379'],
            ['nama' => 'SUKRI RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100380'],
            ['nama' => 'TEPUK HARI RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100381'],
            ['nama' => 'MONPRI RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100382'],
            ['nama' => 'MUHAMMAD RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100383'],
            ['nama' => 'MUS MULYADI RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100384'],
            ['nama' => 'INDRANA RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100385'],
            ['nama' => 'SAHRUL B RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100386'],
            ['nama' => 'Z SIAGIAN RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100387'],
            ['nama' => 'HAIDI NOFRIZAL RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100388'],
            ['nama' => 'M BASYIR RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100389'],
            ['nama' => 'ZEN HAMID HSB RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100390'],
            ['nama' => 'M SIREGAR RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100391'],
            ['nama' => 'SUHAIMI RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100392'],
            ['nama' => 'RM NADEAK RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100393'],
            ['nama' => 'HENDRI IRAWAN RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100394'],
            ['nama' => 'AMIR SAL RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100395'],
            ['nama' => 'IRFAN LUBIS RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100396'],
            ['nama' => 'KARTOLO RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100397'],
            ['nama' => 'ABDI MUDA RIZAL RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100398'],
            ['nama' => 'SULAIMAN EFFENDI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100399'],
            ['nama' => 'SYAHRIAL RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100400'],
            ['nama' => 'MARZUKI RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100401'],
            ['nama' => 'M. JAPARUDDIN RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100402'],
            ['nama' => 'FARYANTO', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100403'],
            ['nama' => 'PARDEDE / JOHARI YADI RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100404'],
            ['nama' => 'MUGI RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100405'],
            ['nama' => 'SABLIANSYAH RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100406'],
            ['nama' => 'MARWAN RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100407'],
            ['nama' => 'ARJUNA WIJAYA RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100408'],
            ['nama' => 'YUFRIZAN RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100409'],
            ['nama' => 'ILHAM RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100410'],
            ['nama' => 'M SIAGIAN RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100411'],
            ['nama' => 'MARIZAL RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100412'],
            ['nama' => 'AKP ISKANDAR RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100413'],
            ['nama' => 'HASMAN HIDAYAT RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100414'],
            ['nama' => 'FAISAL RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100415'],
            ['nama' => 'S. SITUMORANG RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100416'],
            ['nama' => 'SUTEJO RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100417'],
            ['nama' => 'HARMAINI LUBIS RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100418'],
            ['nama' => 'HERMAN NAZAR RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100419'],
            ['nama' => 'U. SIANAGA RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100420'],
            ['nama' => 'SUHIRMAN RD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100421'],
            ['nama' => 'HAMRI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100422'],
            ['nama' => 'SUNARTI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100423'],
            ['nama' => 'ZULKIFLI KOBAT', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100424'],
            ['nama' => 'DJAMAD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100425'],
            ['nama' => 'ABU BAKAR', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100426'],
            ['nama' => 'MNS DUSUN PNP', 'nik' => '', 'kk' => '', 'golongan_id' => 1, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100427'],
            ['nama' => 'LUMBAN TORUAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100428'],
            ['nama' => 'KTR REJE PNP', 'nik' => '', 'kk' => '', 'golongan_id' => 5, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100429'],
            ['nama' => 'THOMAS TARIGAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100430'],
            ['nama' => 'YAHYA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100431'],
            ['nama' => 'SALMIAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100432'],
            ['nama' => 'SAHRIAL APRI, SH', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100433'],
            ['nama' => 'DRS ISMAIL MELALA SAGI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100434'],
            ['nama' => 'FENIE TERIANA ADRIAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100435'],
            ['nama' => 'JUNAIDI, S.TH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100436'],
            ['nama' => 'EDY ROHANI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100437'],
            ['nama' => 'SRI RAHAYU', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100438'],
            ['nama' => 'RUHDI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100439'],
            ['nama' => 'SITI AISYAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100440'],
            ['nama' => 'MAHDALENA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100441'],
            ['nama' => 'DANCEN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100442'],
            ['nama' => 'MHD SUKRI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100443'],
            ['nama' => 'AYUSIARA PUTRI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100444'],
            ['nama' => 'R MERY S', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100445'],
            ['nama' => 'EVI SASTRINA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100446'],
            ['nama' => 'IR TAGORE. MM', 'nik' => '', 'kk' => '', 'golongan_id' => 6, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100447'],
            ['nama' => 'ZULKARNAIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100448'],
            ['nama' => 'RAMLAH HERZIANY', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100449'],
            ['nama' => 'MUZAKIR WALAD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100450'],
            ['nama' => 'AMINAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100451'],
            ['nama' => 'MARIYATUN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100452'],
            ['nama' => 'AZZAN 1', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100453'],
            ['nama' => 'AZZAN 2', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100454'],
            ['nama' => 'AZZAN 3', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100455'],
            ['nama' => 'MANSYUR ALAMSYAH 1', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100456'],
            ['nama' => 'MANSYUR ALAMSYAH 2', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100457'],
            ['nama' => 'M YUSUF ', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100458'],
            ['nama' => 'PAUZAN 1', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100459'],
            ['nama' => 'PAUZAN 2', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100460'],
            ['nama' => 'ASNAINI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100461'],
            ['nama' => 'ZAINAL ABIDIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100462'],
            ['nama' => 'I F A N', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100463'],
            ['nama' => 'HOTMAN SINAGA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100464'],
            ['nama' => 'RUKAYAH USRI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100465'],
            ['nama' => 'SURYANTO', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100466'],
            ['nama' => 'PAK LEO', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100467'],
            ['nama' => 'ILHAM', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100468'],
            ['nama' => 'SUMARNI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '51', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100469'],
            ['nama' => 'RIDWAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100470'],
            ['nama' => 'CHANDRA MAULIDA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100471'],
            ['nama' => 'IBRAHIM TAROSA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100472'],
            ['nama' => 'AKLI AMRAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100473'],
            ['nama' => 'ARDI KONTER', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100474'],
            ['nama' => 'AMAN TAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100475'],
            ['nama' => 'M. THAIB', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100476'],
            ['nama' => 'ARMADA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100477'],
            ['nama' => 'SIMIN 2', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100478'],
            ['nama' => 'SALMAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100479'],
            ['nama' => 'HENDRA JAYA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100480'],
            ['nama' => 'HARUN. S', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100481'],
            ['nama' => 'NURASYID', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100482'],
            ['nama' => 'DAHLAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100483'],
            ['nama' => 'ISKANDAR', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100484'],
            ['nama' => 'SILAHUDDIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100485'],
            ['nama' => 'ABD. QAIDIR', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100486'],
            ['nama' => 'MARDIAH ARI NOSAR', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100487'],
            ['nama' => 'AJI DAUD', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100488'],
            ['nama' => 'MUHAMMAD YUSUF', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100489'],
            ['nama' => 'HALIDIN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100490'],
            ['nama' => 'MAIRIZAL', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100491'],
            ['nama' => 'MAYAANG MURNI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100492'],
            ['nama' => 'ALI NUZAR', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100493'],
            ['nama' => 'JURNALIS', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100494'],
            ['nama' => 'AGUS SALIM GANI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100495'],
            ['nama' => 'M. KASIM', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100496'],
            ['nama' => 'ZURAIDAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100497'],
            ['nama' => 'WABDA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100498'],
            ['nama' => 'SATINAH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100499'],
            ['nama' => 'HAMIDI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100500'],
            ['nama' => 'AFRIZAL', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100501'],
            ['nama' => 'HERWANSYAH, ST', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100502'],
            ['nama' => 'KTR DESA BALE ATU', 'nik' => '', 'kk' => '', 'golongan_id' => 5, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100503'],
            ['nama' => 'IRHAMNA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100504'],
            ['nama' => 'ANDI', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100505'],
            ['nama' => 'HAMIDAH SANTIANA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100506'],
            ['nama' => 'IDA', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100507'],
            ['nama' => 'ALI AMRAN', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100508'],
            ['nama' => 'AINAL LIDA. CH', 'nik' => '', 'kk' => '', 'golongan_id' => 3, 'pdam_id' => 1, 'desa_id' => '133', 'user_id' => 1, 'user_id_penyetuju' => 1, 'nolama' => '1010100509'],


        ]);
    }
}
